GRID_HORIZONTAL_COUNT = 10
GRID_VERTICAL_COUNT = 10

GRAVITY_DECELERATE = 0.8
VELOCITY_FALL_MAX = -10
FRICTION_DECELERATE = 0.5
VELOCITY_MOVE = 10
DISTANCE_ZERO_THRESHOLD = 0.2
GRAVITY_VELOCITY_START = 0.2
