GRID_HORIZONTAL_COUNT = 8
GRID_VERTICAL_COUNT = 8

VELOCITY_JUMP = 20
GRAVITY_DECELERATE = 0.8
VELOCITY_FALL_MAX = -10
FRICTION_DECELERATE = 0.2
VELOCITY_MOVE_MAX = 4
VELOCITY_MOVE_MAX_AIR = 2
VELOCITY_MOVE_STEP = 1
DISTANCE_ZERO_THRESHOLD = 0.2
GRAVITY_VELOCITY_START = 0.2

EVENT_EAT_TRY = 'eat_try'  # ARG: BoundedElement
EVENT_EAT_SUCCESS = 'eat_success'
EVENT_WALK_START = 'walk_start'
EVENT_WALK_STOP = 'walk_stop'
EVENT_GAME_START = 'game_start'
