GRID_HORIZONTAL_COUNT = 8
GRID_VERTICAL_COUNT = 8

VELOCITY_JUMP = 15
GRAVITY_DECELERATE = 0.7
VELOCITY_FALL_MAX = -10
FRICTION_DECELERATE = 0.2
VELOCITY_MOVE = 6
VELOCITY_MOVE_AIR = 2
DISTANCE_ZERO_THRESHOLD = 0.2
GRAVITY_VELOCITY_START = 0.2
